### ISSUE TITLE
occasional blank build console

### ISSUE THREAD

**Issue by superfell** [Shippable/support#1391]
I've seen this a few times today, there's a build shown as in progress, and has been running for a while, but when i go and look at the details, the console tab is empty. Its not clear if the build is running but the console isn't showing anything, or if nothing is actually happening.

![image](https://cloud.githubusercontent.com/assets/399098/7404354/206abc7a-ee96-11e4-8d40-77f9c514eafd.png)

**Comment by bbradbury** [comment]
Us too-- most of our builds are timed out or doing this today

**Comment by alexanderlamb** [comment]
This has been ongoing for a few weeks.  Anecdotally deleting old builds and then manually running the build seems to improve the chances of it successfully starting a new build to ~50%

**Comment by manishas** [comment]
we have a fix for the console issue and we're in the process of testing it.

@bbradbury @alexanderlamb we'll take a look at what's going on with your builds.

**Comment by bbradbury** [comment]
Hung: https://app.shippable.com/builds/55417dc44dd3670e00327cf0
Timed out: https://app.shippable.com/builds/55415046e2a2e30c00c16355

**Comment by manishas** [comment]
@bbradbury I see your latest builds for the project have passed. I hope you're not still running into timeouts and frozen builds. Can you please let us know?

@alexanderlamb please let us know if this happens again and if you point me to specific builds, we can track down the issue.

@superfell the last couple of days were not the best days for us and we had some issues with timeouts/frozen builds and overall slowness. We've fixed most of them and the tail end is being worked on today. Is this still happening for you?

**Comment by alexanderlamb** [comment]
@manishas 
https://app.shippable.com/builds/5543cda442da970c000ef2d3

I'll add more as they appear

**Comment by bbradbury** [comment]
@manishas Yes most our our recent builds have been working, I've kicked off some now on projects that had timed out a few days ago. If there are problems will advise, but I think we're back in business. Thx!

**Comment by superfell** [comment]
@manishas  Haven't seen this issue today.

**Comment by alexanderlamb** [comment]
![image](https://cloud.githubusercontent.com/assets/5480111/7459714/c3cd1bd2-f252-11e4-9e78-5cb4001908ca.png)

https://app.shippable.com/builds/5547bada42da970c000f103d

@manishas 
At least 50% of our builds are still hanging.

**Comment by alexanderlamb** [comment]
@manishas 
![image](https://cloud.githubusercontent.com/assets/5480111/7462495/b95b592a-f266-11e4-9ded-7c282adc3df1.png)

https://app.shippable.com/builds/5547dbec42da970c000f1390

**Comment by alexanderlamb** [comment]
![image](https://cloud.githubusercontent.com/assets/5480111/7463740/e65616c2-f270-11e4-861c-06e99416c5e3.png)

https://app.shippable.com/builds/5547ee7b42da970c000f1510

**Comment by superfell** [comment]
Hit this again today
https://app.shippable.com/builds/5548f4c742da970c000f2812

**Comment by manishas** [comment]
@superfell is this still an issue? I know we've pushed several changes in this area so checking in. We're continuing to improve console streaming so you'll see further improvements, but let me know if the blank console issue still persists.

**Comment by lekhab** [comment]
@superfell: please re-open if the blank console problem still persists. closing out this issue for now.
