### ISSUE TITLE
We no longer have access to the subscription data on the UI

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#1967]
We no longer have access to our data in the Shippable UI. However, **builds still run when we push commits on bitbucket**.

### Home page
On https://app.shippable.com/, I see "No builds have been triggered yet." and there is no mention of our team.

### Subscription page
When I go to https://app.shippable.com/subscriptions/547c792bd46935d5fbbf0b11 as pquentin (signed in from bitbucket), I get "You don't have sufficient permissions to perform this operation" in a red alert box. (And the spinner never stops.)

### Build page
When I go to a specific build, eg. https://app.shippable.com/builds/5629cbf3954d220c00b56fab, I get the following message in the red alert box:

    {
      "id":1004,
      "message":"GET failed for subscriptionId :547c792bd46935d5fbbf0b11",
      "methodName":"caller:54f477fa5ab6cc1352906167|projects|chkPermForId:54c8b9d15ab6cc13528a0671|_getSubPermBySubId",
      "link":401
    }

The page itself displays "Build not found".

What's going on? Thanks!

**Comment by rageshkrishna** [comment]
Hi @pquentin. The problem is that a couple of the API calls that we make to BitBucket to synchronize project and organization permissions have suddenly started reporting errors. We have contacted BitBucket to let them know about the issue.

Your build history and all other information is still present on Shippable, but because the permissions synchronization is running in to an error you're unable to view the data on your dashboard.

I will update this issue as soon as we have more information from BitBucket.

**Comment by Ivaylo-Bachvarov** [comment]
Same problem here. :beers:

**Comment by rmossuk** [comment]
same here

**Comment by pquentin** [comment]
@rageshkrishna Thank you for the explanation.

I don't think BitBucket returning errors should lock us out of Shippable. BitBucket has had issues since two days, who knows how long this is going to take? I expect that they will receive less traffic on Saturday and Sunday, this could allow you to get back the correct settings and stop updating them when you get errors.

Sorry if I'm misunderstanding the issue here.

**Comment by rageshkrishna** [comment]
@pquentin You're absolutely right.

We regularly purge old permissions to make sure that when you remove collaborators from your projects, they also lose access to those projects on Shippable. Unfortunately, a bug in our sync routine allowed the purge to happen even though we were not able to get any new permissions from BitBucket. We're working on fixing this.

**Comment by czardoz** [comment]
Bitbucket is down: http://status.bitbucket.org/

**Comment by j1fig** [comment]
I imagine this should be somehow related to the series of DDoS attacks bitbucket has been under the last 24h.

See the [status](http://status.bitbucket.org/) and [Twitter](https://twitter.com/Bitbucket/status/657240015999770624) updates for latest info.

**Comment by avinci** [comment]
I don't think it was a bug on Shippable. The way permissions work is we sync from bitbucket on a periodic basis. If BB returns an empty array we assume that all perms have been removed from the source and hence remove the perms from our side. Due to BB has significant issues, sometimes we are not getting the right response from BB. This is causing inconsistencies.

We don't remove any web hooks etc when user perms are synced and hence the data should all be fine. The moment BB issues are resolved and then you login in, the system should get back to normal.

Hope this helps

**Comment by leonfs** [comment]
Bitbucket seems to be fully operational now, but the problem still persists. Any news about it?

**Comment by catskul** [comment]
We're curious as well. Can't deploy without shippable being back up.

**Comment by avinci** [comment]
can you force sync in the your account page?

**Comment by avinci** [comment]
Auto Sync timing is every 4 hours. If you force it, it will actually do it right away. Let me know if this does not work.

**Comment by leonfs** [comment]
Tried Syncing,  Revoking OAuth from Bitbucket but nothing seems to work. Bitbucket is up, Shippable down.

**Comment by manishas** [comment]
We are looking into this. Even though bitbucket.org might be up, we were getting an error while calling their API... we're looking at this now to see what's going on...

**Comment by manishas** [comment]
This bitbucket issue is affecting us - https://bitbucket.org/site/master/issues/11989/api-calls-are-failing-with-status-code-403

We're following up with them and I will update as soon as we have more information.

**Comment by avinci** [comment]
I think bitbucket has blocked all external access I think. We are working with their support to unblock our ID

**Comment by avinci** [comment]
These are the APIs that we are getting an error on with OAUTH. I have heard back from Bitbucket folks and they are looking into it.

![screen shot 2015-10-23 at 4 46 58 pm](https://cloud.githubusercontent.com/assets/1302035/10707339/f6c76bc0-79a5-11e5-8b00-a9e84df82858.jpg)
![screen shot 2015-10-23 at 4 46 00 pm](https://cloud.githubusercontent.com/assets/1302035/10707340/faa65864-79a5-11e5-884a-0a88dfe65bf6.jpg)

**Comment by manishas** [comment]
This should now be working. Can you force sync your account and confirm that you see your repos/builds?

**Comment by leonfs** [comment]
Perfect!! I confirm you that is working. Thank you very much.
