### ISSUE TITLE
Support multiple notification integrations

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2206]
Currently only one notification integration (e.g. Slack) can be set per project.

It should be possible to add an arbitrary amount of integrations instead, e.g. to have notifications sent to multiple Slacks.

**Comment by mbrodala** [comment]
@manishas Could it be that this was implemented with the infra change recently? I was just able to add more than one Slack notification to the integrations of one project.

On that regard: is it necessary to configure `notifications` in the YML after adding them this way? At least the 1st integration works just fine on every project I've added it.

**Comment by mbrodala** [comment]
Correction: the 2nd integration was put first after adding it and only this one did send a notification, the other one did not. Removing the 2nd integration again triggers notifications for the 1st one again.

Is this intended?

**Comment by manishas** [comment]
@mbrodala we enabled multiple hub integrations recently and hence removed the 1 integration restriction. We haven't thoroughly tested it for multiple slacks. The tested portions are -

- multiple notification providers, i.e. send notifications to email,slack, irc at the same time
- multiple recipients, i.e. slack channels, email addresses, irc rooms.

We'll take a look into this and get back to you.

**Comment by stephanielingwood** [comment]
@mbrodala Multiple slack integrations should be working now. Once you've added both slack integrations to your project, your yml will look something like this:

```
integrations:
    notifications:
        - integrationName: slackOne
          type: slack
          recipients:
            - "#channelOne"
            - "@recipientOne"
          branches:
              only:
                - master
          on_success: never
          on_failure: always
        - integrationName: slackTwo
          type: slack
          recipients:
            - "#channelTwo"
          branches:
              only:
                - master
          on_success: never
          on_failure: always
```

If you run into problems with this, please let us know.

**Comment by manishas** [comment]
Closing this, but please let us know if you run into issues and i'll reopen the issue.

**Comment by mbrodala** [comment]
@stephanielingwood Just to make sure that I get it right: do I *have to* add the `integrations` section to my YML to get this working or can I just add both integrations to the project and be done?

(BTW I'd love to skip the "add integration to project in Shippable UI" step but that's a different issue. ;-) )

**Comment by mbrodala** [comment]
I'm still seeing the same behavior [as mentioned above](https://github.com/Shippable/support/issues/2206#issuecomment-192319426)

**Comment by stephanielingwood** [comment]
@mbrodala You'll need to add your Slack notifications in both places - the project and the yml. In the UI, you are adding the Slack integrations to your project as a whole. Then, in your yml, you specify the Slack integration(s), in the format above, that you want for that build. 

If you do that, are you still seeing the problem?

And, thanks for the feedback on the UI step - while we don't have plans to change it in the near future, we'll keep it in mind for future versions. :)

**Comment by mbrodala** [comment]
@stephanielingwood It doesn't really work, maybe I'm doing something wrong. I just added the following snippet to my YML:

```yaml
integrations:
  notifications:
    - integrationName: "Foo Slack build notifications"
      type: slack
    - integrationName: "Bar Slack build notifications"
      type: slack
```

(Yes there are spaces in the integration names since I've created them before the Shippable infra switch.)

I've skipped every other option (and would argue that `type` can be skipped too) since everything else is set in the integration itself already or the assumed defaults are fine with me.

**Comment by himanshu0503** [comment]
@mbrodala : Can you please try adding recipients? Your yml should look like
```yaml
integrations:
  notifications:
    - integrationName: "Foo Slack build notifications"
      type: slack
      recipients: 
        - "#channel1"
        - "#channel2"
    - integrationName: "Bar Slack build notifications"
      type: slack
      recipients: 
        - "#channel3"
```

**Comment by mbrodala** [comment]
@himanshu0503 Did that, still no good. I'm not getting any notifications at all ATM. This is how it looks like currently:

```yaml
integrations:
  notifications:
    - integrationName: "Foo Slack build notifications"
      type: slack
      recipients:
        - "#shippable"
    - integrationName: "Bar Slack build notifications"
      type: slack
      recipients:
        - "#shippable"
```

**Comment by himanshu0503** [comment]
@mbrodala : My bad, I forgot to tell about the flags, you need to add the `on_start, on_success, on_failure` flags to tell us for what all scenario's you want to receive notifications. These take in `always and never` values.

```yaml
integrations:
  notifications:
    - integrationName: "Foo Slack build notifications"
      type: slack
      on_failure: always
      on_start: always
      on_success: always
      recipients:
        - "#shippable"
    - integrationName: "Bar Slack build notifications"
      type: slack
      on_failure: always
      on_start: always
      on_success: always
      recipients:
        - "#shippable"
```

**Comment by mbrodala** [comment]
@himanshu0503 Now it works. But since this is rather verbose is it possible that Shippable can assume some useful defaults here?

**Comment by bittner** [comment]
I'm really having a hard time accepting that I can't add the hook URL value to the configuration file. This breaks my "infrastructure as code" understanding.

**Comment by manishas** [comment]
@bittner we want to standardize how integrations with third party services are handled, and that is the main reason behind needing an account integration for everything.

@mbrodala we do have defaults for the triggers:

```
on_success: change
on_failure: always
on_start: never
```

We will retest this to make sure it works as expected.

**Comment by manishas** [comment]
@vidyar can you test this and make sure the slack notifications work as expected?
