### ISSUE TITLE
Build fails while generating meta-data: Database error

### ISSUE THREAD

**Issue by kevinvandervlist** [Shippable/support#2241]
While trying to run shippable on a new repo we experience the following error:

![image](https://cloud.githubusercontent.com/assets/833325/12941129/ad7893ec-cfcf-11e5-9003-bdfa83061730.png)

Or in text:
* Validating commit data
* Error while generating build for branch master
* Error occurred while generating build meta-data: Database error

This happens with a simple Go project. The shippable build job is [to-increase/go-config](https://app.shippable.com/projects/56b8f2451895ca4474739b7d). Any clues?

**Comment by kevinvandervlist** [comment]
Any updates on this? 

To add some more info: [here](https://bitbucket.org/to-increase/go-config/src/8951d56a587a9806f89cc04a0435800111ba8edc/shippable.yml?fileviewer=file-view-default) is the shippable yaml, but the failure occurs before any build steps are executed. 

Mentioning @rlcomte to stay in the loop.

**Comment by rvdwijngaard** [comment]
I am getting the same issue on one of [my builds](https://app.shippable.com/builds/56c6faf79785a20c009c69f7)

**Comment by kevinvandervlist** [comment]
The changes related to today's 'Meet the New Shippable' did not resolve or fix this.

@manishas: can you help us?

**Comment by manishas** [comment]
@a-murphy @trriplejay  can you take a look?

**Comment by trriplejay** [comment]
@kevinvandervlist To take advantage of the new Shippable build system, you'll have to switch your plan on your subscription's billing tab to the one called "Continuous Delivery".  Once you've switched you can try your build again.  The error you were experiencing should be fixed on the new plan.

**Comment by rvdwijngaard** [comment]
@trriplejay we have migrated our subscription to "Continuous Delivery" but the problem remains. Please take a look at https://app.shippable.com/builds/56e66cee97449d0c00d440d5.

**Comment by rageshkrishna** [comment]
@rvdwijngaard It looks like your subscription is still on the "Single Tenant CI" plan. Can you please confirm whether the change in plan was successful? Did you get any errors while trying to change the plan?

**Comment by manishas** [comment]
Closing this. Please let us know if this is still not working and we can take a look.

**Comment by kevinvandervlist** [comment]
We switched to the new plan this morning, it indeed looks like the error is gone.

**Comment by manishas** [comment]
:+1:
