### ISSUE TITLE
IE11 does not work for any site on shippable.com

### ISSUE THREAD

**Issue by bakersemail** [Shippable/support#2756]
At work I am forced to use IE11 but the shippable website does not load.
It gets stuck on the first page with a spinning loading wheel.

A javascript error appears in the debug window (if open). Screenshot available at http://i.imgur.com/xdGKqXV.png

This is severely hampering us from adopting shippable at my workplace.

**Comment by manishas** [comment]
@harryi3t we need to look at this....

**Comment by rageshkrishna** [comment]
@bakersemail We've identified the problem and will have a fix deployed in the next day or two at the most.

**Comment by rageshkrishna** [comment]
@bakersemail This should be working now. Please give it a shot and let me know if you still see any issues. Thanks!

**Comment by bakersemail** [comment]
Thanks. Verified working.

**Comment by bakersemail** [comment]
Sorry. I was testing at home and it was working but when I got into work it's still broken. Broken for a different reason and I cannot see any errors in IE11 debugger.
Screenshot available at: http://i.imgur.com/YTj7ilT.png

**Comment by rageshkrishna** [comment]
@bakersemail At first glance, this seems to be something specific to your environment because I'm unable to repro the error here and it also works for you on another machine.

Would it be possible for you to send me a screenshot of the network tab when this error happens that shows the details of the call that failed? You can email me at ragesh@shippable.com if you'd rather not share it here. Thanks!

**Comment by rageshkrishna** [comment]
@bakersemail Any luck with this? Is there anything I can do to help debug this further?

**Comment by bakersemail** [comment]
Hi rageshkrishna:

The error is still happening. Here's a copy of the network tab shown in IE11. I have also included the request headers, response headers and response body:

<blockquote class="imgur-embed-pub" lang="en" data-id="a/N65Mu"><a href="//imgur.com/N65Mu"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

Request headers:

Key	Value
Request	GET /accounts HTTP/1.1
Accept	application/json, text/plain, */*
Referer	https://app.shippable.com/
Accept-Language	en-AU
Origin	https://app.shippable.com
Accept-Encoding	gzip, deflate, peerdist
User-Agent	Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Host	api.shippable.com
DNT	1
Connection	Keep-Alive
Cache-Control	no-cache
X-P2P-PeerDist	Version=1.1
X-P2P-PeerDistEx	MinContentInformation=1.0, MaxContentInformation=2.0


Response headers:

Key	Value
X-Powered-By	Express
Response	HTTP/1.1 500 Internal Server Error
ETag	"1437044202"
Date	Mon, 11 Jul 2016 05:57:12 GMT
Content-Type	application/json; charset=utf-8
Content-Length	119
Connection	Keep-Alive
Age	0
Access-Control-Allow-Origin	*
Access-Control-Allow-Methods	GET,PUT,POST,DELETE
Access-Control-Allow-Headers	Accept,Content-Type,Authorization,Cookie
Access-Control-Allow-Credentials	true

Response body:

{"logType":"error","methodName":"accounts|getS|callerId:public|_getAccount","id":666,"message":"accountsModel.findOne"}

**Comment by rageshkrishna** [comment]
It looks like IE isn't sending an Authorization header with this request (This is why you see a `callerId:public` in the response body). Is there anything on your work network that might be blocking cookies for any reason? You should see an `apiToken` cookie as soon as you log in.

**Comment by bakersemail** [comment]
Hi rageshkrishna,

There shouldnt be, but I will check with our infrastructure provider. 
So I should have received a cookie called apiToken which is sent in this subsequent request?

**Comment by rageshkrishna** [comment]
Hi @bakersemail, sorry for not getting back sooner... the API request should have an Authorization header. The value we put in to the header comes from a cookie called `apiToken` that should be set on your session when you log in. We don't send the cookie itself in the API call. I suspect you're not getting this cookie for some reason.

Unfortunately I'm still unable to repro this locally.

**Comment by bakersemail** [comment]
Hi @rageshkrishna,

The cookie appears to be being set by app.shippable.com and is being sent in requests like https://app.shippable.com/ngApp/scripts/home/home.html. Looks like nothing like an apiToken or Authorization header is sent to the api.shippable.com domain.

**Comment by rageshkrishna** [comment]
@bakersemail I've tried a bunch of things to try and reproduce this but still haven't been successful. To summarize where we are on this:

1. Shippable works for you with IE11 at home, but not at work.

1. You see the apiToken cookie, but do not see an Authorization header with the cookie's value in requests being sent to api.shippable.com when at work.

We have rolled out a series of updates recently, but nothing specifically to address this issue. Can you please give it another shot and let me know if this is exactly what's happening now?

I'm still leaning towards some kind of group policy or something similar in your work network that is triggering this, but I can't really point to anything specific at this time. The fact that it works for you at home makes it highly unlikely that the issue is with IE11 support in general.
