### ISSUE TITLE
Various serious problems with Shippable

### ISSUE THREAD

**Issue by rlcomte** [Shippable/support#3259]
### Description of your issue:
Over the months we have encountered a number of serious problems with Shippable:

1. Browser cookies get randomly invalidated, forcing one to manually delete them and do a fresh login
2. Quite often we need to perform a 'clear build cache' in order to repair a build
3. Some (NodeJS, Scala) builds fail unexpectedly although they build correctly on local machines, and they build when retried several times. 
4. Backward compatibility is not maintained when changes to build process, build file or other Shippable components are made. A case: Android builds broke because Shippable scripts suddenly required a build image tag instead of using the implicit 'latest' tag, as Docker supports.
5. Builds are not predictable, which impacts our ability to quickly fix, build and release our software.

We are spending a number of hours each week on Shippable issues, which should not be necessary.

**Comment by avinci** [comment]
@rlcomte we are looking into this, I will get back to you with an update. Thanks very much for the feedback .

**Comment by avinci** [comment]
@rlcomte 
In the last 6 weeks we have been constantly hardening the platform so that the flakiness is removed. 
Here are the following things we have done
- harden the webhook processing which was getting dropped due to various flakiness of our system and sometimes CDN issues SCM providers
- UI had been standardized to manage auth and this should resolve the issues that you were facing with cookies. If these persist please let us know as we rarely touch auth pieces and not sure why this might be happening
- build stability has been a focus. We have added retry commands on most of the external dependencies and it should reduce this. But then again i would recommend using `shippable_retry` if you are making network calls. We use AWS as our backend and we cannot predict their network load when your builds run. Let me know if you are seeing this randomly or in specific places. We might be able to address them by hardening it
- backwards compatibility, We try our best to make it backwards compatible. The thing that we have not done well is retire old syntax and code that causes newer version to break. I take this a valid feedback and we will do better around this. We are starting to retire old syntax and implicit assumptions across the board. This is critical for us to have a reliable and predictable build system, The unfortunate part is we did not make explicitness as a principle of ours and we are now. I hope this should reduce drastically moving forward and create stability across the platform.

Please let me know if you have any concerns or questions and I am happy to jump on a call and address them further.

**Comment by rlcomte** [comment]
Thanks for the update. We will check a number of the issues we had and if
problems persist we will let you know.

Met vriendelijke groet, kind regards,

Rine le Comte

M rlcomte@gmail.com
