### ISSUE TITLE
CI minions stuck over an hour on paid account

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3387]
### Description of your issue:
CI build stuck on the below status for over 1 hours
```Provisioning a node for subscriptionId: 583638aafd9c101000d73b34```

- Link to the build failure => https://app.shippable.com/runs/58ae6d1232ce931100169ecd/1/console

![image](https://cloud.githubusercontent.com/assets/15203863/23246469/ec06a8c2-f9e7-11e6-8927-bb04107fe81e.png)

**Comment by kanthchandra** [comment]
@asanchezgiraldo I'm looking into it. We will get back to you with our findings in some time.

**Comment by kanthchandra** [comment]
@asanchezgiraldo Did you by any chance pause and unpause the project for which the builds are stuck?

**Comment by kanthchandra** [comment]
Hi @asanchezgiraldo there was a bug at our end where in we were not setting some properties correctly when the project is paused and as a result although the node came up, your build wouldn't start correctly because some properties were missing. I have manually set those properties for you and future builds should work correctly for you. Please let us know if you run into such issues again.

We have already fixed the bug and it's in staging environment and will be deployed to production sometime tomorrow. So until then please dont pause the project from the project settings page. If you really want to pause it you can pause it from the pipelines page. Sorry for the inconvenience.

**Comment by asanchezgiraldo** [comment]
@kanthchandra I am still not able to run my CI builds.

It seems all started when I added the below to the build ci section

`    - echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/now-site-img.env
`

and also added the below job

```
# sync pipeline to CI
  - name: now-site_runCI
    type: runCI
    steps:
      - OUT: now-site-img
```

**Comment by kanthchandra** [comment]
@asanchezgiraldo Did you pause and unpause the ci project?

**Comment by asanchezgiraldo** [comment]
@kanthchandra I did not before your comment.

But I did after your comment as was unsure if the project was paused before.

Before I paused and un-paused the project, the CI build was not starting after your fix on my project.

**Comment by kanthchandra** [comment]
Ok, I will fix a couple things at my end. Please dont do anything at your end. After this I'll let you know after my changes are done.

**Comment by kanthchandra** [comment]
I'll need to cancel the jobs that are running right now in order to fix this. I hope that's ok.

**Comment by asanchezgiraldo** [comment]
@kanthchandra yes that is ok to cancel the jobs

**Comment by kanthchandra** [comment]
@asanchezgiraldo I think the problem is fixed and I have triggered a run for you on the master branch. Can you please test this and let me know if it works?

P.S Please DO NOT pause the project. We have a bug fix which needs to be deployed and it will be done tomorrow.

**Comment by asanchezgiraldo** [comment]
@kanthchandra thanks for that, I can see the master branch is running, I will try my other branch now.

Thanks for your help

**Comment by kanthchandra** [comment]
I'm assuming this is not an issue any more. Closing.
