### ISSUE TITLE
Do not run commands in Docker container

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3696]
For [some usecases](https://github.com/Shippable/support/issues/3525) it would be useful if one could completely steer the build on the build host machine, e.g. if build commands start Docker containers which leads to issues e.g. with volume paths. There are [workarounds](http://docs.shippable.com/ci/docker-compose/) but they don't work in all circumstances.

A good example is the [Docker support in Semaphore CI](https://semaphoreci.com/docs/docker.html): instead of automatically launching a build container and executing build commands in that container, selecting the platform with Docker support simply preinstalls the Docker daemon and CLI client. This way one can easily execute arbitrary commands, among others to launch Docker containers.

**Comment by ambarish2012** [comment]
@mbrodala I will add this feature request to our backlog.

**Comment by mbrodala** [comment]
Thanks. :-) Let me know if you need more info.

**Comment by ambarish2012** [comment]
@mbrodala  we have implemented this feature. After you upgrade your subscription to the latest release, you can execute a  runSh job on the host as shown [here](http://docs.shippable.com/platform/tutorial/workflow/using-runSh/#running-a-task-on-the-host).

**Comment by mbrodala** [comment]
That's really great to hear! How can I reflect this with a `shippable.yml` only? Right now we don't use any resources or jobs and so far I wasn't able to grasp the whole concept or make it versatile enough like our current `shippable.yml`.

**Comment by ambarish2012** [comment]
@mbrodala if you need help, we can jump into a quick call and I can help you get your first assembly line setup with jobs and resources.

**Comment by mbrodala** [comment]
@ambarish2012 Thanks for the offer, maybe you can already add some explanation here. I still don't get how Assembly Lines are supposed to work. So far I only know the typical CI approach with having a single config file in each repository telling the CI server what to do on build.

For example I understand how to add a `syncRepo` but I still don't understand how I can instruct Shippable to execute jobs using resources defined in a `syncRepo` on arbitrary other repositories. I imagine a setup like this:

- one or more central `syncRepo`s where I define the full workflow for build and deploy for our project types
- arbitrary `ciRepo`s just like now which refer to their `syncRepo` and pass in some data if necessary

The [docs about jobs](http://docs.shippable.com/platform/tutorial/workflow/crud-job/) are still unclear to me so far.

**Comment by ambarish2012** [comment]
@mbrodala happy to help you understand how to setup assembly lines and we can also go over this in a quick call. 

To execute jobs on a specific repository, you will need to do the following:

1. Create a [gitRepo](http://docs.shippable.com/platform/workflow/resource/gitrepo/#gitrepo) resource that points to your repository in a shippable.yml file. The gitRepo resource can be configured to trigger on commits, prs, releases etc.
2. Create a [runSh](http://docs.shippable.com/platform/workflow/job/runsh/) job with the gitRepo resource as an input in a shippable.yml file.
3. Create a syncRepo for the repository and branch where you created the shippable.yml. After you create the syncRepo using the UI, we will create the jobs and resources and you can trigger them manually as well from the SPOG.

When the runSh job executes (which can also use any docker image) it will checkout the git repository and execute your script code. Your script code  can then run arbitrary build commands in the checked out repository. If you are using Shippable images in your runSh job and you use the same tag as your AMI, we won't even pull any image since those images are already there in the AMI.

Here is a sample you can look at: https://github.com/ambarish2012/dotnet-framework-docker-samples/blob/master/shippable.yml.

**Comment by mbrodala** [comment]
I tried to reproduce this in [this repository](https://bitbucket.org/mbrodala/shippable-jobs/). But as soon as I remove all code related to CI from the `shippable.yml` I get a [broken build](https://app.shippable.com/bitbucket/mbrodala/shippable-jobs/runs/4/1/console).

This is what my `shippable.yml` currently looks like:

```yaml
resources:
  - name: shippable_jobs_test
    type: gitRepo
    integration: bitbucket
    pointer:
      sourceName: mbrodala/shippable-jobs
      branch: master

jobs:
  - name: container_single_task
    type: runSh
    steps:
      - IN: shippable_jobs_test
      - TASK:
          name: task
          script:
            - uname -a
```

My SPOG view:

![image](https://user-images.githubusercontent.com/5037116/36834564-8e744776-1d33-11e8-9e8e-7d9883802ad4.png)

My _Enable Project_ view:

![image](https://user-images.githubusercontent.com/5037116/36834618-bb2bb876-1d33-11e8-9b4b-955e7c4291af.png)

Any idea what's wrong here?

**Comment by trriplejay** [comment]
runCI operates on the main "ci" sections of the shippable.yml.  runSh is a different job type that should show as a different rectangle in your SPOG.  The runCI is failing because the yml no longer has any instructions for it to follow.

However, your runSh and sync jobs aren't showing in your subscription.  It looks like this might be a permissions issue related to the project being moved to a different subscription.  It looks like the syncRepo was added when the repo belonged to a different organization, and now the repo has been moved on the source control.  We're taking steps to correct the permissions in the back end.  

Once corrected, you should see your runSh job as a separate job that you can run manually, or that will be triggered whenever your 'shippable-jobs' repo is updated.

**Comment by trriplejay** [comment]
update: actually it looks like the syncRepo will have to be re-added in this new subscription. I think pipeline-enabled resources and jobs do not transfer well between subscriptions at this time. 

Now that we've cleaned this up, you'll need to go to the 'enable project' page and add your sync repo again to this new sub.  Then you should see your syncRepo, rSync job, runSh job, and gitRepo all in your spog.  At that point, you can run the runSh job and you should see it execute the script you listed above.

You may want to pause your runCI job since there is no script for it to run at this time.  This will prevent it from getting a failure every time you update your repo.

**Comment by mbrodala** [comment]
You are absolutely right, I moved the Git repository around a few times and I guess that did confuse the Shippable server. Now I can indeed that the [`runSh` task is executed successfully](https://app.shippable.com/bitbucket/mbrodala/jobs/container_single_task/dashboard).

So this basically means that the Git repository I have now is a `gitRepo` and `syncRepo` at the same time, whereas the latter means whatever resources and jobs I define in the `shippable.ym` are created globally for my subscription?

How could I disable the `runCI` job? Not doing this would allow me to e.g. add some validation/linting to the `gitRepo` itself, right?

Given the current state how would I change the set up to have arbitrary Git repositories use the resources/jobs defined in the `syncRepo`? Adding a `syncRepo` for each and every Git repository does not seem to make sense, especially when all resources and jobs are then defined globally for the subscription; I'd need to add prefixes/suffixes to the `name`s to avoid conflicts AFAIS.

**Comment by trriplejay** [comment]
for any git repository that you want to use, you can define a `gitRepo` resource (http://docs.shippable.com/platform/workflow/resource/gitrepo/)  This will setup to receive webhook similarly to how an enabled CI project works.  You can define a gitRepo resource for any project in your subscription and put it in any shippable.yml in any syncRepo in your subscription.  You could have a single syncRepo that supports your entire pipeline and all your projects, or you could split it up in whatever way makes logical sense to you.

so if you had 5 projects and you wanted 5 scripts, you would define 5 gitRepos and use them an IN steps to 5 runSh scripts, all in the same shippable.yml in the same syncRepo.  All jobs within a subscription will have access to all other resources/jobs in the subscription, regardless of which syncRepo they came from (unless you specifically set up more strict permissions).

If you want to disable your runCI, there are a couple ways.  The easiest thing is to disable webhooks by going to the project settings page, and flipping the toggle at the top:
![image](https://user-images.githubusercontent.com/6869398/37182426-161d19e8-22e6-11e8-87c4-5568a1f012b7.png)

You could also scroll to the bottom of the settings and actually "delete" the project.  This would remove the runCI from your pipeline and delete any history that you might have. your syncRepo would remain enabled.

does that answer your questions?

**Comment by mbrodala** [comment]
Honestly this is very complex to understand and configure and takes a lot of time to get working.

Would it be possible to add the `container: false` option to the `build` section of the `shippable.yml` too?

The whole build would then run on the host similar to the assembly lines setup.

**Comment by trriplejay** [comment]
I'm not sure that we intend to enhance CI in this way, but I'll open an internal issue to discuss it and let you know.

**Comment by mbrodala** [comment]
Thanks for your understanding. :-)

**Comment by manishas** [comment]
@mbrodala implementing this would require a major change to our CI architecture, so the plan for the time being is to support the 'run on host' capability through runSh.

If you try the Assembly Line config one time, I'm confident you'll find it much easier than you expected :) Happy to jump on a call and show you how to configure a runSh job.... also if you find gaps in runSh when compared to CI jobs, we'll be happy to add that functionality to runSh.

**Comment by mbrodala** [comment]
By now I finally understand how assembly lines work and think I can get this to work once I need to tackle this again. Thanks for the explanation!
